name: somum_utilities
description: A starting point for Dart libraries or applications.
version: 1.0.0+0
publish_to: none
environment:
  sdk: '>=3.1.4 <4.0.0'
dependencies:
  apollocode_dart_utilities:
    git:
      url: https://apollocode-ca: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@github.com/apollocode-ca/dart_utilities
      ref: 4.3.0
  collection: ^1.18.0
  mongo_dart: ^0.9.3
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.9
